# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 13:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdresatNadawca',
            fields=[
                ('id_adresata_nadawcy', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=255, unique=True)),
                ('miasto', models.CharField(max_length=255)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('ulica', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'adresat_nadawca',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdresKontrahent',
            fields=[
                ('id_adresu', models.AutoField(primary_key=True, serialize=False)),
                ('miasto', models.CharField(max_length=45)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('ulica', models.CharField(max_length=45)),
                ('czy_domyslny', models.NullBooleanField()),
            ],
            options={
                'db_table': 'adres_kontrahent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdresOsoba',
            fields=[
                ('id_adresu', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=20)),
                ('czy_domyslny', models.NullBooleanField()),
            ],
            options={
                'db_table': 'adres_osoba',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id_dokumentu', models.AutoField(primary_key=True, serialize=False)),
                ('tytul_dokumentu', models.TextField()),
                ('nazwa_pliku', models.CharField(max_length=255)),
                ('data_dodania', models.DateField()),
            ],
            options={
                'db_table': 'dokument',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kontrahent',
            fields=[
                ('id_kontrahenta', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_krotka', models.CharField(max_length=50, verbose_name='Nazwa krótka')),
                ('nazwa_dluga', models.CharField(max_length=255, verbose_name='Pełna nazwa')),
                ('nip', models.CharField(max_length=10)),
                ('czy_aktywny', models.NullBooleanField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('telefon', models.CharField(blank=True, max_length=45, null=True)),
                ('notatka', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kontrahent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Korespondencja',
            fields=[
                ('id_korespondencji', models.AutoField(primary_key=True, serialize=False)),
                ('numer_korespondencji', models.CharField(blank=True, max_length=60, null=True)),
                ('temat', models.CharField(max_length=255)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('data_przyjscia_wyjscia', models.DateField()),
                ('rodzaj', models.CharField(choices=[('Wychodząca', 'Wychodząca'), ('Przychodząca', 'Przychodząca')], default=('Przychodząca', 'Przychodząca'), max_length=255)),
                ('adresat_nadawca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escrm.AdresatNadawca')),
            ],
            options={
                'db_table': 'korespondencja',
                'ordering': ['-numer_korespondencji'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_oferty', models.AutoField(primary_key=True, serialize=False)),
                ('temat', models.CharField(max_length=255)),
                ('produkt', models.CharField(max_length=255)),
                ('termin_waznosci', models.DateField(verbose_name='Termin ważności')),
                ('wartosc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wartość')),
                ('akceptacja', models.NullBooleanField()),
                ('data_sporzadzenia', models.DateField(verbose_name='Data sporządzenia')),
                ('waluta', models.CharField(default='PLN', max_length=3)),
                ('kontrahent', models.ForeignKey(db_column='kontrahent', on_delete=django.db.models.deletion.PROTECT, to='escrm.Kontrahent')),
                ('oferta_rodzic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escrm.Oferta')),
            ],
            options={
                'db_table': 'oferta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id_osoby', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=60)),
                ('nazwisko', models.CharField(max_length=60)),
                ('stanowisko', models.CharField(max_length=100)),
                ('notatka', models.TextField(null=True)),
                ('kontrahent', models.ManyToManyField(to='escrm.Kontrahent')),
            ],
            options={
                'db_table': 'osoba',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Platnosc',
            fields=[
                ('id_platnosci', models.AutoField(primary_key=True, serialize=False)),
                ('termin', models.DateField()),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kwota_zaksiegowana', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'platnosc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlikKorespondencji',
            fields=[
                ('id_pliku_korespondencji', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_pliku', models.CharField(max_length=255)),
                ('sciezka_do_pliku', models.CharField(max_length=255)),
                ('korespondencja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escrm.Korespondencja')),
            ],
            options={
                'db_table': 'plik_korespondencji',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=15)),
                ('stanowisko', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StatusOferty',
            fields=[
                ('id_statusu_oferty', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_statusu', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'status_oferty',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StatusUmowy',
            fields=[
                ('id_statusu', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'status_umowy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TypAdresu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'typ_adresu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TypZdarzenia',
            fields=[
                ('id_typu', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_zdarzenia', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'typ_zdarzenia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Umowa',
            fields=[
                ('id_umowy', models.AutoField(primary_key=True, serialize=False)),
                ('temat', models.CharField(max_length=255)),
                ('produkt', models.CharField(max_length=255)),
                ('termin_waznosci', models.DateField(null=True, verbose_name='Termin ważności')),
                ('data_platnosci', models.DateField(null=True, verbose_name='Data płatności')),
                ('data_sporzadzenia', models.DateField(verbose_name='Data sporządzenia')),
                ('termin_platnosci', models.IntegerField(verbose_name='Termin płatności')),
                ('waluta', models.CharField(max_length=3)),
                ('wartosc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wartość')),
                ('kontrahent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escrm.Kontrahent')),
                ('opiekun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='escrm.Profil')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escrm.StatusUmowy')),
            ],
            options={
                'db_table': 'umowa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Zdarzenie',
            fields=[
                ('id_zdarzenia', models.AutoField(primary_key=True, serialize=False)),
                ('data_zdarzenia', models.DateTimeField()),
                ('temat', models.CharField(max_length=255)),
                ('notatka', models.TextField()),
                ('kontrahent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escrm.Kontrahent')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escrm.TypZdarzenia')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escrm.Profil')),
            ],
            options={
                'db_table': 'zdarzenie',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='platnosc',
            name='umowa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escrm.Umowa'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='opiekun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='escrm.Profil'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escrm.StatusOferty'),
        ),
        migrations.AddField(
            model_name='korespondencja',
            name='uzytkownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escrm.Profil'),
        ),
        migrations.AddField(
            model_name='kontrahent',
            name='opiekun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escrm.Profil'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='oferta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='escrm.Oferta'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='umowa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='escrm.Umowa'),
        ),
        migrations.AddField(
            model_name='dokument',
            name='uzytkownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escrm.Profil'),
        ),
        migrations.AddField(
            model_name='adresosoba',
            name='osoba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escrm.Osoba'),
        ),
        migrations.AddField(
            model_name='adreskontrahent',
            name='kontrahent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escrm.Kontrahent'),
        ),
        migrations.AddField(
            model_name='adreskontrahent',
            name='typ_adresu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='escrm.TypAdresu'),
        ),
    ]
