# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platnosc',
            options={'managed': True, 'ordering': ['termin']},
        ),
    ]
