# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import escrm.models


class Migration(migrations.Migration):

    dependencies = [
        ('escrm', '0002_auto_20180207_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='data_dodania',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='nazwa_pliku',
            field=models.FileField(max_length=255, upload_to=escrm.models.set_upload_path),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='tytul_dokumentu',
            field=models.CharField(max_length=255, verbose_name='Tytuł dokumentu'),
        ),
    ]
