# Generated by Django 2.2.6 on 2019-11-23 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escrm', '0003_auto_20180209_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='oferta_rodzic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='escrm.Oferta'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='imie',
            field=models.CharField(max_length=60, verbose_name='Imię'),
        ),
    ]
