# Generated by Django 4.2 on 2023-05-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrm', '0004_auto_20191123_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adreskontrahent',
            name='czy_domyslny',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adresosoba',
            name='czy_domyslny',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kontrahent',
            name='czy_aktywny',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='akceptacja',
            field=models.BooleanField(default=False),
        ),
    ]
